 @echo off

start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%
start %random%

stop "%random%"